package domain

// DefaultNigerianBanks is a comprehensive Nigerian bank list (NIBSS/CBN NUBAN
// codes) used to populate the winner payout form when the money rail does not
// return a full list (e.g. the sandbox). Sorted by name; deduped by code and
// name. Source: public NUBAN bank directory (Paystack /bank, retrieved 2026-09).
var DefaultNigerianBanks = []NigerianBank{
	{Code: "51455", Name: "5TT MFB"},
	{Code: "40195", Name: "78 Finance Company Ltd"},
	{Code: "090629", Name: "9jaPay Microfinance Bank"},
	{Code: "120001", Name: "9mobile 9Payment Service Bank"},
	{Code: "404", Name: "Abbey Mortgage Bank"},
	{Code: "51204", Name: "Above Only MFB"},
	{Code: "51312", Name: "Abulesoro MFB"},
	{Code: "044", Name: "Access Bank"},
	{Code: "063", Name: "Access Bank (Diamond)"},
	{Code: "602", Name: "Accion Microfinance Bank"},
	{Code: "090759", Name: "Advancly MFB"},
	{Code: "50315", Name: "Aella MFB"},
	{Code: "90077", Name: "AG Mortgage Bank"},
	{Code: "50036", Name: "Ahmadu Bello University Microfinance Bank"},
	{Code: "120004", Name: "Airtel Smartcash PSB"},
	{Code: "51336", Name: "AKU Microfinance Bank"},
	{Code: "090561", Name: "Akuchukwu Microfinance Bank Limited"},
	{Code: "50055", Name: "Al-Barakah Microfinance Bank"},
	{Code: "51074", Name: "Alert MFB"},
	{Code: "50059", Name: "ALLWORKERS MFB"},
	{Code: "108", Name: "Alpha Morgan Bank"},
	{Code: "000304", Name: "Alternative bank"},
	{Code: "50926", Name: "Amju Unique MFB"},
	{Code: "50083", Name: "Aramoko MFB"},
	{Code: "401", Name: "ASO Savings and Loans"},
	{Code: "50092", Name: "Assets Microfinance Bank"},
	{Code: "090478", Name: "AVUENEGBE MICROFINANCE BANK"},
	{Code: "51351", Name: "AWACASH MICROFINANCE BANK"},
	{Code: "51337", Name: "AZTEC MICROFINANCE BANK LIMITED"},
	{Code: "51229", Name: "Bainescredit MFB"},
	{Code: "50117", Name: "Banc Corp Microfinance Bank"},
	{Code: "11072", Name: "Bank78 Microfinance Bank"},
	{Code: "50572", Name: "BANKIT MFB"},
	{Code: "51341", Name: "BANKLY MFB"},
	{Code: "51212", Name: "BC Kash Microfinance Bank"},
	{Code: "51100", Name: "BellBank Microfinance Bank"},
	{Code: "51267", Name: "Benysta Microfinance Bank Limited"},
	{Code: "50122", Name: "Berachah Microfinance Bank Ltd."},
	{Code: "50123", Name: "Beststar Microfinance Bank"},
	{Code: "51411", Name: "BLOC MFB"},
	{Code: "50725", Name: "BOLD MFB"},
	{Code: "51449", Name: "Boost Microfinance Bank"},
	{Code: "650", Name: "Bosak Microfinance Bank"},
	{Code: "50931", Name: "Bowen Microfinance Bank"},
	{Code: "90070", Name: "Brent Mortgage bank"},
	{Code: "50645", Name: "BuyPower MFB"},
	{Code: "565", Name: "Carbon"},
	{Code: "51353", Name: "Cashbridge Microfinance Bank Limited"},
	{Code: "865", Name: "CASHCONNECT MFB"},
	{Code: "51437", Name: "Cedrus MFB"},
	{Code: "50823", Name: "CEMCS Microfinance Bank"},
	{Code: "050032", Name: "Centrum Finance"},
	{Code: "50171", Name: "Chanelle Microfinance Bank Limited"},
	{Code: "312", Name: "Chikum Microfinance bank"},
	{Code: "023", Name: "Citibank Nigeria"},
	{Code: "070027", Name: "CITYCODE MORTAGE BANK"},
	{Code: "50186", Name: "Civic Microfinance Bank Limited"},
	{Code: "50910", Name: "Consumer Microfinance Bank"},
	{Code: "51458", Name: "Cool Microfinance Bank Limited"},
	{Code: "50204", Name: "Corestep MFB"},
	{Code: "559", Name: "Coronation Merchant Bank"},
	{Code: "40119", Name: "Credit Direct Limited"},
	{Code: "51297", Name: "Crescent MFB"},
	{Code: "090560", Name: "Crust Microfinance Bank"},
	{Code: "50216", Name: "CRUTECH MICROFINANCE BANK LTD"},
	{Code: "51368", Name: "Dash Microfinance Bank"},
	{Code: "51334", Name: "Davenport MICROFINANCE BANK"},
	{Code: "51450", Name: "Dillon Microfinance Bank"},
	{Code: "50162", Name: "Dot Microfinance Bank"},
	{Code: "50922", Name: "EBSU Microfinance Bank"},
	{Code: "050", Name: "Ecobank Nigeria"},
	{Code: "50263", Name: "Ekimogun MFB"},
	{Code: "098", Name: "Ekondo Microfinance Bank"},
	{Code: "50280", Name: "ESO-E MICROFINANCE BANK LIMITED"},
	{Code: "51475", Name: "Ethica MFB"},
	{Code: "090678", Name: "EXCEL FINANCE BANK"},
	{Code: "50126", Name: "Eyowo"},
	{Code: "51318", Name: "Fairmoney Microfinance Bank"},
	{Code: "51241", Name: "FCMB MFB"},
	{Code: "50298", Name: "Fedeth MFB"},
	{Code: "050002", Name: "Fewchore Finance Company Limited"},
	{Code: "51110", Name: "FFS Microfinance Bank"},
	{Code: "070", Name: "Fidelity Bank"},
	{Code: "51314", Name: "Firmus MFB"},
	{Code: "011", Name: "First Bank of Nigeria"},
	{Code: "214", Name: "First City Monument Bank"},
	{Code: "090164", Name: "FIRST ROYAL MICROFINANCE BANK"},
	{Code: "51333", Name: "FIRSTMIDAS MFB"},
	{Code: "413", Name: "FirstTrust Mortgage Bank Nigeria"},
	{Code: "090567", Name: "Flutterwave MFB"},
	{Code: "501", Name: "FSDH Merchant Bank Limited"},
	{Code: "832", Name: "FUTMINNA MICROFINANCE BANK"},
	{Code: "812", Name: "Gateway Mortgage Bank LTD"},
	{Code: "00103", Name: "Globus Bank"},
	{Code: "090574", Name: "Goldman MFB"},
	{Code: "100022", Name: "GoMoney"},
	{Code: "090664", Name: "GOOD SHEPHERD MICROFINANCE BANK"},
	{Code: "50739", Name: "Goodnews Microfinance Bank"},
	{Code: "562", Name: "Greenwich Merchant Bank"},
	{Code: "51276", Name: "GROOMING MICROFINANCE BANK"},
	{Code: "50368", Name: "GTI MFB"},
	{Code: "058", Name: "Guaranty Trust Bank"},
	{Code: "51251", Name: "Hackman Microfinance Bank"},
	{Code: "90065", Name: "Haggai Mortgage Bank"},
	{Code: "50383", Name: "Hasal Microfinance Bank"},
	{Code: "51364", Name: "Hayat Trust MFB"},
	{Code: "120002", Name: "HopePSB"},
	{Code: "51211", Name: "IBANK Microfinance Bank"},
	{Code: "51279", Name: "IBBU MFB"},
	{Code: "51244", Name: "Ibile Microfinance Bank"},
	{Code: "90012", Name: "Ibom Mortgage Bank"},
	{Code: "50439", Name: "Ikoyi Osun MFB"},
	{Code: "50442", Name: "Ilaro Poly Microfinance Bank"},
	{Code: "50453", Name: "Imowo MFB"},
	{Code: "415", Name: "IMPERIAL HOMES MORTAGE BANK"},
	{Code: "50457", Name: "Infinity MFB"},
	{Code: "070016", Name: "Infinity trust Mortgage Bank"},
	{Code: "090701", Name: "ISUA MFB"},
	{Code: "301", Name: "Jaiz Bank"},
	{Code: "402", Name: "Jubilee Life Mortgage Bank"},
	{Code: "50502", Name: "Kadpoly MFB"},
	{Code: "51308", Name: "KANOPOLY MFB"},
	{Code: "5129", Name: "Kayvee Microfinance Bank"},
	{Code: "082", Name: "Keystone Bank"},
	{Code: "899", Name: "Kolomoni MFB"},
	{Code: "100025", Name: "Kolomoni Microfinance Bank"},
	{Code: "50200", Name: "Kredi Money MFB LTD"},
	{Code: "50211", Name: "Kuda Bank"},
	{Code: "90052", Name: "Lagos Building Investment Company Plc."},
	{Code: "091003", Name: "Lemmy MFB"},
	{Code: "090420", Name: "Letshego Microfinance Bank"},
	{Code: "50549", Name: "Links MFB"},
	{Code: "031", Name: "Living Trust Mortgage Bank"},
	{Code: "50491", Name: "LOMA MFB"},
	{Code: "303", Name: "Lotus Bank"},
	{Code: "51444", Name: "Maal MFB"},
	{Code: "090171", Name: "MAINSTREET MICROFINANCE BANK"},
	{Code: "51474", Name: "Mayden Microfinance Bank"},
	{Code: "50563", Name: "Mayfair MFB"},
	{Code: "50570", Name: "Mega Microfinance Bank"},
	{Code: "50304", Name: "Mint MFB"},
	{Code: "946", Name: "Money Master PSB"},
	{Code: "50515", Name: "Moniepoint MFB"},
	{Code: "120003", Name: "MTN Momo PSB"},
	{Code: "090190", Name: "MUTUAL BENEFITS MICROFINANCE BANK"},
	{Code: "090679", Name: "NDCC MICROFINANCE BANK"},
	{Code: "51361", Name: "NET MICROFINANCE BANK"},
	{Code: "51142", Name: "Nigerian Navy Microfinance Bank Limited"},
	{Code: "51304", Name: "NIRSAL MICROFINANCE"},
	{Code: "50072", Name: "Nombank MFB"},
	{Code: "561", Name: "NOVA BANK"},
	{Code: "51371", Name: "Novus MFB"},
	{Code: "50629", Name: "NPF MICROFINANCE BANK"},
	{Code: "51261", Name: "NSUK MICROFINANACE BANK"},
	{Code: "51392", Name: "NUVION MFB"},
	{Code: "50689", Name: "Olabisi Onabanjo University Microfinance Bank"},
	{Code: "50697", Name: "OLUCHUKWU MICROFINANCE BANK LTD"},
	{Code: "999992", Name: "OPay Digital Services Limited (OPay)"},
	{Code: "107", Name: "Optimus Bank Limited"},
	{Code: "51477", Name: "Pact Microfinance Bank"},
	{Code: "100002", Name: "Paga"},
	{Code: "999991", Name: "PalmPay"},
	{Code: "104", Name: "Parallex Bank"},
	{Code: "311", Name: "Parkway - ReadyCash"},
	{Code: "090680", Name: "PATHFINDER MICROFINANCE BANK LIMITED"},
	{Code: "51457", Name: "Paystack MFB"},
	{Code: "100039", Name: "Paystack-Titan"},
	{Code: "50743", Name: "Peace Microfinance Bank"},
	{Code: "51226", Name: "PECANTRUST MICROFINANCE BANK LIMITED"},
	{Code: "51146", Name: "Personal Trust MFB"},
	{Code: "50746", Name: "Petra Mircofinance Bank Plc"},
	{Code: "050021", Name: "PFI FINANCE COMPANY LIMITED"},
	{Code: "268", Name: "Platinum Mortgage Bank"},
	{Code: "00716", Name: "Pocket App"},
	{Code: "076", Name: "Polaris Bank"},
	{Code: "50864", Name: "Polyunwana MFB"},
	{Code: "105", Name: "PremiumTrust Bank"},
	{Code: "050023", Name: "PROSPERIS FINANCE LIMITED"},
	{Code: "101", Name: "Providus Bank"},
	{Code: "51293", Name: "QuickFund MFB"},
	{Code: "502", Name: "Rand Merchant Bank"},
	{Code: "090496", Name: "RANDALPHA MICROFINANCE BANK"},
	{Code: "50130", Name: "Rank MFB"},
	{Code: "90067", Name: "Refuge Mortgage Bank"},
	{Code: "50761", Name: "REHOBOTH MICROFINANCE BANK"},
	{Code: "50994", Name: "Rephidim Microfinance Bank"},
	{Code: "51375", Name: "Retrust Mfb"},
	{Code: "51108", Name: "Rex Microfinance Bank"},
	{Code: "51286", Name: "Rigo Microfinance Bank Limited"},
	{Code: "50767", Name: "ROCKSHIELD MICROFINANCE BANK"},
	{Code: "50622", Name: "RSU MICROFINANCE BANK"},
	{Code: "125", Name: "Rubies MFB"},
	{Code: "51113", Name: "Safe Haven MFB"},
	{Code: "40165", Name: "SAGE GREY FINANCE LIMITED"},
	{Code: "50582", Name: "Shield MFB"},
	{Code: "106", Name: "Signature Bank Ltd"},
	{Code: "51062", Name: "Solid Allianze MFB"},
	{Code: "50800", Name: "Solid Rock MFB"},
	{Code: "51310", Name: "Sparkle Microfinance Bank"},
	{Code: "50756", Name: "SPECTRUM MFB LTD"},
	{Code: "51429", Name: "Springfield Microfinance Bank"},
	{Code: "221", Name: "Stanbic IBTC Bank"},
	{Code: "068", Name: "Standard Chartered Bank"},
	{Code: "090162", Name: "STANFORD MICROFINANCE BANK"},
	{Code: "50809", Name: "STATESIDE MICROFINANCE BANK"},
	{Code: "070022", Name: "STB Mortgage Bank"},
	{Code: "51253", Name: "Stellas MFB"},
	{Code: "232", Name: "Sterling Bank"},
	{Code: "00305", Name: "Summit Bank"},
	{Code: "100", Name: "Suntrust Bank"},
	{Code: "50968", Name: "Supreme MFB"},
	{Code: "302", Name: "TAJ Bank"},
	{Code: "51269", Name: "Tangerine Money"},
	{Code: "109", Name: "Tatum Bank"},
	{Code: "51403", Name: "TENN"},
	{Code: "677", Name: "Think Finance Microfinance Bank"},
	{Code: "102", Name: "Titan Bank"},
	{Code: "090708", Name: "TransPay MFB"},
	{Code: "51118", Name: "TRUSTBANC J6 MICROFINANCE BANK"},
	{Code: "50840", Name: "U and C MFB"},
	{Code: "51396", Name: "UBJ Microfinance Bank Limited"},
	{Code: "090706", Name: "UCEE MFB"},
	{Code: "51322", Name: "Uhuru MFB"},
	{Code: "51080", Name: "Ultraviolet Microfinance Bank"},
	{Code: "51097", Name: "Umunnachi Microfinance Bank Ltd"},
	{Code: "50870", Name: "Unaab Microfinance Bank Limited"},
	{Code: "51447", Name: "UNIABUJA MFB"},
	{Code: "50871", Name: "Unical MFB"},
	{Code: "51316", Name: "Unilag Microfinance Bank"},
	{Code: "50875", Name: "UNIMAID MICROFINANCE BANK"},
	{Code: "032", Name: "Union Bank of Nigeria"},
	{Code: "033", Name: "United Bank For Africa"},
	{Code: "215", Name: "Unity Bank"},
	{Code: "50880", Name: "UNIUYO Microfinance Bank Ltd"},
	{Code: "50894", Name: "Uzondu Microfinance Bank Awka Anambra State"},
	{Code: "050020", Name: "Vale Finance Limited"},
	{Code: "566", Name: "VFD Microfinance Bank Limited"},
	{Code: "51085", Name: "Victory MFB"},
	{Code: "51355", Name: "Waya Microfinance Bank"},
	{Code: "035", Name: "Wema Bank"},
	{Code: "51386", Name: "Weston Charis MFB"},
	{Code: "402001", Name: "Whitecrust Finance Company"},
	{Code: "100040", Name: "Xpress Wallet"},
	{Code: "594", Name: "Yes MFB"},
	{Code: "057", Name: "Zenith Bank"},
	{Code: "51373", Name: "Zitra MFB"},
}
